version: '3'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vue-app
    container_name: cms-vue-container
    ports:
      - "8080:8080"
    volumes:
      - .:/app