version: '3'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    image: vue-app
    container_name: cms-vue-container
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: /bin/sh -c "npm install && npm run serve"